/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeInfo {
  id: number
  surface: string
  feature: string
  len: number
  rcAttr: number
  lcAttr: number
  posid: number
  charType: number
  stat: number
  isbest: number
  alpha: number
  beta: number
  prob: number
  cost: number
}
export declare function sum(a: number, b: number): number
export declare function parseAsNode(input: string): Array<NodeInfo>
